### PR TITLE
[releng] Update Sirius 7.0.4 and Kitalpha

### PR DESCRIPTION
**Pull request by pdulth**
Change-Id: Ic65c91f29b8bd11aa5fabdc12139dd528ebda85f
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>

### CODE REVIEW

**Comment by pdulth** [comment]
(still missing Kitalpha)

**Comment by pcdavid** [comment]
@pdulth I just noticed that Sirius 7.0.4rc1 is impacted by https://github.com/eclipse-tycho/tycho/issues/1281. Since 7.0.3 we moved from Tycho 2.7.1 to 2.7.4 and this changes the content of the p2 repo produced by our build. More specifically, the new 7.0.4rc1 repo contains the following features that were not in Sirius repos before:



I'd like to [revert to Tycho 2.7.1](https://git.eclipse.org/r/c/sirius/org.eclipse.sirius/+/195318) and rebuild for the 7.0.4 final release to minimize the impact.
Is it still possible for Capella (and KitAlpha) to consume Sirius 7.0.4 from a new URL?

**Comment by pdulth** [comment]
> @pdulth I just noticed that Sirius 7.0.4rc1 is impacted by [eclipse-tycho/tycho#1281](https://github.com/eclipse-tycho/tycho/issues/1281). Since 7.0.3 we moved from Tycho 2.7.1 to 2.7.4 and this changes the content of the p2 repo produced by our build. More specifically, the new 7.0.4rc1 repo contains the following features that were not in Sirius repos before:
> 
> 
> 
> I'd like to [revert to Tycho 2.7.1](https://git.eclipse.org/r/c/sirius/org.eclipse.sirius/+/195318) and rebuild for the 7.0.4 final release to minimize the impact. Is it still possible for Capella (and KitAlpha) to consume Sirius 7.0.4 from a new URL?

sure, tell us when the 7.0.4 is ok

**Comment by pcdavid** [comment]
A respin built with Tycho 2.7.1 is available at https://download.eclipse.org/sirius/updates/releases/7.0.4/2021-06/
I confirmed the p2 repo is back to its previous content (without the additional features). There is no code change compared to the rc1, just a rebuild with a different version of Tycho.

**Review by minhtutonthat — APPROVED** [review]

**Pull request merged**
